[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = UIABXXutQe7MHiITvpXHJHqa2FxYnA0Hj0X0713x7Ho=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = 2+vSMIT9/NeS/H80xGUXYC0ingHzgl5a9UF2/Bc23zQ=
PresharedKey = rAQ2tfnZ4kaPEn7d0kAD6rgfbZ/2HqE8g/n8Kg/QCE8=
AllowedIPs = 10.13.13.2/32

[Peer]
# peer2
PublicKey = 4lpl9yixP4iZNg6DKwjbftLRjOy7Euve2Soyrrcq5l4=
PresharedKey = 22Gv7Lki9mmn1defUeQ4krNj1qFGRrzSmqclBo0/0ig=
AllowedIPs = 10.13.13.3/32

