# nginx/nginx.conf

# -------------------------------------------------------------
# BLOCO 1: PÚBLICO (CLOUDFARE/NGROK) - PORTA 80
# Objetivo: Servir o site em HTTP para o túnel externo, sem redirecionar
#           para que o Cloudflare possa funcionar.
# -------------------------------------------------------------
server {
    listen 80;
    server_name _; 
		server_tokens off;
		add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
		add_header X-Content-Type-Options "nosniff";
		add_header X-Frame-Options "SAMEORIGIN";
    location / {
        # IMPORTANTE: Força o cabeçalho HTTPS para o Django
        proxy_set_header X-Forwarded-Proto https; 
        
        # Passa o tráfego para o Django
        proxy_pass http://web:8000;
        
        # Cabeçalhos padrão
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# -------------------------------------------------------------
# BLOCO 2: ACESSO LOCAL / DESENVOLVIMENTO (PORTA 8000)
# Objetivo: Redirecionar acessos locais que chegam em HTTP para o HTTPS local.
# -------------------------------------------------------------
server {
    listen 8000; # Escuta na porta 8000 do host, que é HTTP
    server_name localhost 127.0.0.1 172.16.10.101; # Define os hosts locais
		server_tokens off;
		add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
		add_header X-Content-Type-Options "nosniff";
		add_header X-Frame-Options "SAMEORIGIN";
    # Redireciona TUDO o que chegar em HTTP (porta 8000) para HTTPS 8443
    return 301 https://$host:8443$request_uri;
}

# -------------------------------------------------------------
# BLOCO 3: HTTPS LOCAL (PORTA 8443)
# Objetivo: Servir o tráfego seguro que vem do redirecionamento 
#           (ou acesso direto https://localhost:8443).
# -------------------------------------------------------------
server {
    listen 8443 ssl; 
    server_name localhost 127.0.0.1 172.16.10.101; # Define os hosts locais
		server_tokens off;
    # Certificados
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
		
		add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
		add_header X-Content-Type-Options "nosniff";
		add_header X-Frame-Options "SAMEORIGIN";
		
    # Cabeçalhos de Segurança (Nikto Fixes)
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https; 
    }
}
