[Interface]
Address = 10.13.13.3
PrivateKey = uCs3JPs7lUMGZDkWkpxB9RrqoaInALcHUEyBCitm1Xc=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = qEaBv+IGAjkAAoO96VqM9EBKDky+3lKSJ3XZ+k94Qg4=
PresharedKey = 22Gv7Lki9mmn1defUeQ4krNj1qFGRrzSmqclBo0/0ig=
Endpoint = 179.218.10.56:51820
AllowedIPs = 0.0.0.0/0, ::/0
