# Generated by Django 4.2.25 on 2025-10-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
