# Generated by Django 4.2.25 on 2025-10-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blockedip_blocknetwork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockNetwork',
            new_name='BlockedNetwork',
        ),
    ]
