[Interface]
Address = 10.13.13.2
PrivateKey = sHIoiXjG/Ctx5y9qaMNGwAnu2Gnk0tJXyYIgTXxyz0E=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = qEaBv+IGAjkAAoO96VqM9EBKDky+3lKSJ3XZ+k94Qg4=
PresharedKey = rAQ2tfnZ4kaPEn7d0kAD6rgfbZ/2HqE8g/n8Kg/QCE8=
Endpoint = 179.218.10.56:51820
AllowedIPs = 0.0.0.0/0, ::/0
