# Generated by Django 4.2.26 on 2025-11-25 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='secure_docs/')),
                ('classification', models.CharField(choices=[('PUBLIC', 'Publico (Acesso Livre)'), ('INTERNAL', 'Interno (Requer Login)'), ('CONFIDENTIAL', 'Confidencial (Requer VPN)')], default='INTERNAL', max_length=20)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('is_encrypted', models.BooleanField(default=False, editable=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
